services:
    manuel.dev_access.security.access_config:
        class: Manuel\Bundle\DevAccessBundle\Security\AccessConfig
        arguments:
            - '@filesystem'
            - 'E:\\www\\dev_seguridad\\var\\cache'
